name: ci

on: [push, pull_request]

jobs:
  deno:
    name: publish-on-tag
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test -A

      - name: Publish on tag
        # note: if you're copying this, replace main.ts with
        # jsr:@david/publish-on-tag@x.x.x but replace x.x.x
        # with the pinned version of this package
        run: deno run -A src/main.ts
